### ISSUE TITLE
Crash with VD, VDXR latest UEVR nightly

### ISSUE THREAD

**Issue by Zod1234** [deterministicj/Remnant1-UEVR#2]
As discussed, here's the crash.  For a little context, I'm early in the game, in the sewers.  The crash happened with several tries, but didn't seem entirely random.    It seemed to crash when the first mini-boss of the sewers would show.  The dude with two blades, the gunner, etc those guys.  One would show and about 5 seconds later it would crash.   Played a few hours with uevr without this plugin and no crashes.

win 11, 32 gig, nvidia 4070. quest 2.
[UE4CCremnant.zip](https://github.com/user-attachments/files/18246782/UE4CCremnant.zip)

**Comment by Zod1234** [comment]
CJ117 replicated the bug.  markmon's dll available on discord seems to have resolved the issue.

**Comment by CYB3R-JUNKI3** [comment]
Thanks for the update.
I'll mark this as resolved.
